[package]
name = "quepaxa"
description = "An implementation of the Quepaxa consensus algorithm"
version = "0.0.0"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/cberner/quepaxa"
authors = ["Christopher Berner <me@cberner.com>"]

[dependencies]
